name: Express Docker CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  express-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "%{{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 via Docker Compose
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER}}@${{ secrets.SERVER_HOST }} << 'EOF'
              cd /home/${{ secrets.SERVER_USER }}//fe
              docker compose pull
              docker compose up -d
          
